name: Deploy to Vercel

on:
  push:
    branches:
      - main   # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build    # or your build command

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}     # Find in Vercel dashboard
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Find in Vercel dashboard
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --confirm --token $VERCEL_TOKEN